feat(cli): demand some ruleset to be present
stoplightio/spectral pull request #1699
Opened 2021-06-29 07:16 UTC by P0lip

Related to #1698 

**Checklist**

- [x] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [x] Yes
- [ ] No

**Additional context**

Bear in mind that this only relevant to the situation where you do not provide a ruleset and have no `.spectral.{js,json,yaml,yml}` at the same time.
We no longer load any default ruleset, thus it's on user now to specify some.

2021-07-06 16:56 UTC, wmhilton requested changes
Can we change the error message for the CLI to say something like "Please provide a ruleset using the --ruleset CLI argument" or maybe just print the standard "Usage: " when it's used incorrectly? (So that users are told how to use it correctly instead of just told an error)

2021-07-06 18:46 UTC, wmhilton approved these changes

2021-07-06 18:47 UTC, wmhilton commented
Thanks!

2021-07-06 18:52 UTC, merged

2021-09-28 16:20 UTC, dolmen commented
My CI build that use the latest version of Spectral to validate OpenAPI specs, now fails because of this change.

Where can I find the upgrade guide that will tell me where I can find a generic ruleset (which was not needed before)? There is nothing helpful in the [CHANGELOG](https://github.com/stoplightio/spectral/blob/develop/CHANGELOG.md#600---2021-07-14).

2021-09-28 18:40 UTC, P0lip commented
Hey @dolmen!
It's in the readme 
![image](https://user-images.githubusercontent.com/9273484/135146378-886a7846-ad1a-4fa4-9b54-540da4c06ea4.png)
```
echo '{\n\t"extends": ["spectral:oas"]\n}' > .spectral.json
```

and we have a more extensive guide about style guides over here https://github.com/stoplightio/spectral/blob/develop/docs/getting-started/3-rulesets.md

2021-09-29 08:35 UTC, dolmen commented
I did this because that's what is written in the [ruleset documentation](https://meta.stoplight.io/docs/spectral/ZG9jOjYyMDc0NA-rulesets#extending-rulesets):

```console
echo 'extends: "spectral:oas"' > .spectral.yml
```

I notice that here `extends` takes a string while you wrote above like it takes an array. Which is right? Is there a built-in ruleset to validate Spectral rulesets?