fix: length.min said "must not be longer than"
stoplightio/spectral pull request #2355
Opened 2022-12-01 23:49 UTC by philsturgeon

The not was a mistake, it should be "must be longer than", but the must is confusing for folks thinking about RFC 2119 MUST, SHOULD, COULD, etc. Let's just go with expectations?

**Checklist**

- [ ] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [x] Yes
- [ ] No

Any change to a message could be considered breaking but this was broken already, so hopefully people arent programatically doing things on string responses.

2022-12-02 01:05 UTC, dotslashderek approved these changes, later dismissed

2022-12-05 12:20 UTC, P0lip requested changes
In such a case, I suppose we should update all messages.
They all use `must` keyword

2022-12-05 18:53 UTC, philsturgeon commented
@P0lip I don't think we should block this on the grounds of consistency. Currently its literally incorrect.

Note that the rule is `if ('min' in opts && value < opts.min) {`

"must not be longer than"

If minimum is 5 characters, and you provide 4 characters, it will say: 

"foo must not be longer than 5 characters"

whiiiich is the opposite of what it means. It means

"foo must be longer than 5 characters"

Can we merge to fix this?

2022-12-11 12:49 UTC, philsturgeon commented
@P0lip @mnaumanali94 this bug is holding up the Documentation ruleset, as right now it's saying "must not be longer than 20 characters" for a shorter than 20 characters description. I'll code the tests with the bug in place but somebody else will need to update that later.

2022-12-12 11:30 UTC, philsturgeon commented
@P0lip redone with minimal change to fix the bug. Can I get a thumb?

2022-12-12 13:18 UTC, P0lip approved these changes

2022-12-12 13:18 UTC, merged