feat(functions): expand xor function and add or function
stoplightio/spectral pull request #2765
Opened 2024-12-21 22:18 UTC by cuttingclyde

Replaces https://github.com/stoplightio/spectral/pull/2616 with addition of independent or function.

Fixes #2396 . This has now been merged with stoplightio:develop containing prior "xor" PR https://github.com/stoplightio/spectral/pull/2614.

**Checklist**

- [X] Tests added / updated
- [X] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

(Just saw JeanArhancet's similar pull request, https://github.com/stoplightio/spectral/pull/2614 .)

FDX (see below) has extended XOR here to support from 1 to any number of properties. This would match the XOR logical function, that as long as exactly one of the (1 or more) properties is defined, then the rule passes. With just one property defined in the functionOptions, xor becomes redundant with defined function.

Updated error response messages to account for possibility of schema matching any number of properties or schema not matching any of any number of functionOption properties.

Updated functionOptions error messages to show example arrays containing from one to three ("and etc") properties.

Since then can take an array which implements AND-ing of rule requirements, this PR also defines and adds a new OR function. OR works just like xor for requiring at least one matching property, but then permits more than one matching property as valid and satisfying the rule.

Updated functions documentation for `xor` changes to allow more than two properties and new `or` function.

**Additional context**

The Financial Data Exchange (FDX, https://financialdataexchange.org) industry consortium for Open Banking delivers 13 OpenAPI 3.1 files with nearly 17,000 lines, 47 paths, 70 operations and 374 defined schemas, We enforce our FDX API Style Guide using 48 custom spectral rules and 23 overrides over 870 ruleset lines. We wanted to enforce that `type` was defined for each schema, but a schema can get its type in 3 (or 4) ways: `type`, `$ref`, or `oneOf` . (We are not using `allOf` to define `type`.) This was ideal for an unresolved xor rule with properties `type`, `$ref`, or `oneOf` . We initially implemented this as a custom function which met our needs, so are now contributing this to the spectral community. Our rule using our custom `xor` function:

``` yaml
  fdx-property-type-defined:
    description: A valid type must be set for each property (fdx-schema-type ensures oneOf and $ref entities have type defined)
    message: '{{property}} property has zero or multiple defined types from: "type", "oneOf", "$ref"'
    severity: error
    given:
      - $..properties[*]
    # Do not resolve here so $ref can be used as xor function option
    resolved: false
    then:
      # This uses custom fdx_xor function which enforces XOR for any number of properties ([TODO] spectral xor only allows 2 values)
      function: fdx_xor
      functionOptions:
        properties:
          - type
          - oneOf
          - $ref
```

Secondly, there is an OR-rule opportunity to ensure that defined schemas contain sufficient documentation, as a style guide requirement. In particular, each schema ought to have its use / purpose described for users, which can be done in any of `title`, `summary`, or `description` fields. This is an ideal place for an `or` function, since any one of those can provide the required schema documentation text, but two or three of them is also just as valid (or better!). A similar example (also included in this PR's tests), would be requiring a helpful example for a `type: string` schema, which could be provided by any of `format`, `example`, or `pattern` fields in the API spec, but again more than one is acceptable.

2025-03-05 21:31 UTC, frankkilcommins requested changes
@cuttingclyde apologies in the delayed review here.

Looks great. Just a few textual adjustments and I'm suggesting that for **XOR** and **OR** usage we should remain at a minimum of two enumerated properties. For singular usage, we'd recommend **defined** as the function.

2025-03-05 21:31 UTC, frankkilcommins commented on docs/reference/functions.md
> +Communicate that one of these properties is required, and no more than one is allowed to be defined. FunctionOptions must contain any non-zero number of properties, **xor** will require that _exactly
```suggestion
Communicate that one of these properties is required, and no more than one is allowed to be defined. `functionOptions` must contain at least two properties and **xor** will require that _exactly_ one of them is defined.
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +        // maxItems: 2, // No maximum limit is necessary, XOR is valid for any amount, just one must be defined
```suggestion
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +        minItems: 1, // XOR is valid with one item (then it is redundant with 'defined' function)
```suggestion
        minItems: 2,
        errorMessage: `"xor" and its "properties" option require at least 2-item tuples, i.e. ["id", "name"]`,
```
IMO, XOR is requiring at least 2 items to compare. We'd be recommending the use of **defined** for singular use case

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/__tests__/or.test.ts
> +  it('given none of 1 property, should return an error message', async () => {
likely to be adjusted assuming we revert minItems to 2 for OR

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/__tests__/or.test.ts
> +  it('given only one of 1 property, should return no error message', async () => {
to be adjusted assuming we revert minItems back to 2 for XOR

2025-03-05 21:31 UTC, frankkilcommins commented on docs/reference/functions.md
> +Communicate that one or more of these properties is required to be defined. FunctionOptions must contain any non-zero number of properties, **or** will require that _at least_ one of them is defined.
```suggestion
Communicate that one or more of these properties is required to be defined. `functionOptions` must contain at least two properties. **or** will require that _at least_ one of them is defined.
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/__tests__/xor.test.ts
> +  it('given none of 1 property, should return an error message', async () => {
likely to be adjusted assuming we revert minItems back to 2 for XOR

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/__tests__/xor.test.ts
> +  it('given only one of 1 property, should return no error message', async () => {
to be adjusted assuming we revert minItems back to 2 for XOR

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/__tests__/xor.test.ts
> +            '"xor" requires one or more enumerated "properties", i.e. ["id"], ["country", "street"], ["one", "two", "three"], etc.',
```suggestion
            '"xor" requires two or more enumerated "properties", i.e. ["country", "street"], ["one", "two", "three"], etc.',
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/__tests__/xor.test.ts
> +            '"xor" requires one or more enumerated "properties", i.e. ["id"], ["country", "street"], ["one", "two", "three"], etc.',
```suggestion
            '"xor" requires at least two enumerated "properties", i.e. ["id"], ["country", "street"], ["one", "two", "three"], etc.',
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +        minItems: 1, // OR is valid with one item (then it is redundant with 'defined' function)
```suggestion
        minItems: 2,
```
IMO, we should recommend usage of **defined** if only one entry is anticipated

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +        // maxItems: 2, // No maximum limit is necessary, OR is valid for any amount, just one must be defined
```suggestion
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +        errorMessage: `"or" requires one or more enumerated "properties", i.e. ["id"], ["default", "example"], ["title", "summary", "description"], etc.`,
```suggestion
        errorMessage: `"or" requires at least two enumerated "properties", i.e. ["default", "example"], ["title", "summary", "description"], etc.`,
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +      type: `"or" function has invalid options specified. Example valid options: { "properties": ["id"] }, { "properties": ["default", "example"] }, { "properties": ["title", "summary", "description"
```suggestion
      type: `"or" function has invalid options specified. Example valid options: { "properties": ["default", "example"] }, { "properties": ["title", "summary", "description"] }, etc.`,
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +      type: `"xor" function has invalid options specified. Example valid options: { "properties": ["id"] }, { "properties": ["country", "street"] }, { "properties": ["one", "two", "three"] }, etc.`,
```suggestion
      type: `"xor" function has invalid options specified. Example valid options: { "properties": ["country", "street"] }, { "properties": ["one", "two", "three"] }, etc.`,
```

2025-03-05 21:31 UTC, frankkilcommins commented on packages/functions/src/optionSchemas.ts
> +        errorMessage: `"xor" requires one or more enumerated "properties", i.e. ["id"], ["country", "street"], ["one", "two", "three"], etc.`,
```suggestion
        errorMessage: `"xor" requires at least two enumerated "properties", i.e. ["country", "street"], ["one", "two", "three"], etc.`,
```

2025-03-07 22:03 UTC, cuttingclyde commented
Updated as requested the best I could. In the year since making this contribution I've switched laptops and am not able to get the tests to run locally by following the CONTRIBUTION.md instructions as I did last year.

2025-03-11 09:42 UTC, frankkilcommins requested changes
Thanks for the adjustments.

I spotted a few minor issues in the tests which if adjusted hopefully will result in them passing.

To pass the **linting** check rules, you will also have to modify your commit messages to follow conventional commits (e.g. `feat(functions): add OR function`)

2025-03-11 09:42 UTC, frankkilcommins commented on packages/functions/src/__tests__/or.test.ts
> +  it('given one property, should show no error message', async () => {
I believe this test will now return an error as Or expects `minItems: 2`

2025-03-11 09:42 UTC, frankkilcommins commented on packages/functions/src/__tests__/or.test.ts
> +            '"or" requires one or more enumerated "properties", i.e. ["default", "example"], ["title", "summary", "description"], etc.',
This does not match what will now be returned by the JSON Schema:
'"or" requires at least two enumerated "properties", i.e. ["default", "example"], ["title", "summary", "description"], etc.'

2025-03-11 09:42 UTC, frankkilcommins commented on packages/functions/src/__tests__/or.test.ts
> +            '"or" requires one or more enumerated "properties", i.e. ["default", "example"], ["title", "summary", "description"], etc.',
This does not match what's now returned by the JSON Schema: '"or" requires at least two enumerated "properties", i.e. ["default", "example"], ["title", "summary", "description"], etc.'

2025-03-11 09:42 UTC, frankkilcommins commented on packages/functions/src/__tests__/xor.test.ts
> +  it('given 1 property, should return no error message', async () => {
This test will now return an error based on `minItems: 2`

2025-03-11 09:42 UTC, frankkilcommins commented on packages/functions/src/__tests__/xor.test.ts
> +    it.each([{ properties: ['foo'] }])('given valid %p options, should not throw', async opts => {
This will likely throw an error now due to `minItems: 2` constraint.

2025-03-18 14:51 UTC, mnaumanali94 commented
@cuttingclyde Would you be able to take a look at the tests - if not, we can potentially look at fixing the tests on our own.

2025-03-18 20:22 UTC, cuttingclyde commented on packages/functions/src/__tests__/or.test.ts
> +  it('given one property, should show no error message', async () => {
I'm not sure how a validation error message would look in Core Functions testing, I've updated with validation error text and commented out for now.

2025-03-18 20:25 UTC, cuttingclyde commented on packages/functions/src/__tests__/xor.test.ts
> +  it('given 1 property, should return no error message', async () => {
Same comment as above, added validation error text and commented out.

2025-03-18 20:29 UTC, cuttingclyde commented on packages/functions/src/__tests__/xor.test.ts
> +    it.each([{ properties: ['foo'] }])('given valid %p options, should not throw', async opts => {
Correct, removed this test both here and in Or tests.

2025-03-18 20:52 UTC, cuttingclyde commented
@mnaumanali94, thanks. I've updated to correct the comments, but am unfortunately still unable to run them locally.
Happy to have any assistance with fixing any test typos that are causing failures.

2025-03-18 21:48 UTC, frankkilcommins requested changes
Thanks @cuttingclyde. Apologies, I missed two tests in my previous review. I've added comments for those now.

Also to pass the lint checks, you need to update all commits to follow conventional commits format. Is that something you can also take care of? 

Thanks in advance.

2025-03-18 21:48 UTC, frankkilcommins commented on packages/functions/src/__tests__/or.test.ts
> +  it('given no properties, should show no error message', async () => {
This test also fails due to `minItems` constraint

2025-03-18 21:48 UTC, frankkilcommins commented on packages/functions/src/__tests__/xor.test.ts
> +  it('given no properties, should return no error message', async () => {
this test also fails due to `minItems` constraint.

2025-03-18 21:54 UTC, cuttingclyde commented on packages/functions/src/__tests__/xor.test.ts
> +  it('given no properties, should return no error message', async () => {
Thanks, I should have caught those too. 😦

2025-03-18 22:00 UTC, cuttingclyde commented
> Also to pass the lint checks, you need to update all commits to follow conventional commits format. Is that something you can also take care of?

Looks like git would require a force push to change older, pushed commit messages of

2025-03-18 22:11 UTC, frankkilcommins commented
> Looks like git would require a force push to change older, pushed messages of prior commits, I';m not familiar with and don't think I'm comfortable doing that.

No problem. I can help you here if needed and update the commit messages on your fork.

> Oh, and it looks like I accidentally closed this PR when first adding this comment, I'll reopen.

😄 no problem at all.

2025-03-20 08:29 UTC, frankkilcommins commented
@cuttingclyde unfortunately I fat fingered one of the commit messages in the rebase and as usual a rebase on top of a rebase is not fun (especially as it's over ~200 commits).

I'm not comfortable in resolving and merging this PR. I'll work on a new PR to supersede this today or tomorrow and attribute the changes to you.

2025-03-20 13:20 UTC, frankkilcommins commented
superseded by #2798

2025-03-20 13:20 UTC, closed without merging